export const GET_ALL_TASKS_PROCESS = "GET_ALL_TASKS_PROCESS"
export const GET_ALL_TASKS_SUCCESS = "GET_ALL_TASKS_SUCCESS"
export const GET_ALL_TASKS_FAIL = "GET_ALL_TASKS_FAIL"

export const GET_SINGLE_TASK_PROCESS = "GET_SINGLE_TASK_PROCESS"
export const GET_SINGLE_TASK_SUCCESS = "GET_SINGLE_TASK_SUCCESS"
export const GET_SINGLE_TASK_FAIL = "GET_SINGLE_TASK_FAIL"

export const CREATE_TASK_PROCESS = "CREATE_TASK_PROCESS"
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS"
export const CREATE_TASK_FAIL = "CREATE_TASK_FAIL"

export const UPDATE_TASK_PROCESS = "UPDATE_TASK_PROCESS"
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS"
export const UPDATE_TASK_FAIL = "UPDATE_TASK_FAIL"

export const DELETE_TASK_PROCESS = "DELETE_TASK_PROCESS"
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS"
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL"

